<?php

declare(strict_types=1);

return [
    /*
    |--------------------------------------------------------------------------
    | Portal Capabilities
    |--------------------------------------------------------------------------
    | Each capability is a module-level switch. Routes, navigation, admin access,
    | and future policies should check capabilities instead of scattering
    | hard-coded feature assumptions across the app.
    */
    'modules' => [
        'jobs' => [
            'label' => 'Jobs',
            'description' => 'Global job search, job details, applications, saved jobs, and job alerts.',
            'enabled' => true,
            'public' => true,
            'admin_section' => 'jobs',
            'phase' => 'Phase 1',
        ],
        'candidates' => [
            'label' => 'Candidates',
            'description' => 'Candidate registration, profile, CV builder, video profile, portfolio, and verification.',
            'enabled' => true,
            'public' => true,
            'admin_section' => 'candidates',
            'phase' => 'Phase 1 / Phase 2',
        ],
        'employers' => [
            'label' => 'Employers',
            'description' => 'Employer registration, dashboard, candidate search, and verification.',
            'enabled' => true,
            'public' => true,
            'admin_section' => 'employers',
            'phase' => 'Phase 1 / Phase 3',
        ],
        'trust_safety' => [
            'label' => 'Trust & Safety',
            'description' => 'Reports, complaints, verification queues, anti-scam rules, and audit controls.',
            'enabled' => true,
            'public' => true,
            'admin_section' => 'trust',
            'phase' => 'Phase 1',
        ],
        'international' => [
            'label' => 'International Support',
            'description' => 'Countries, cities, currencies, languages, visa, relocation, and authorization data.',
            'enabled' => true,
            'public' => true,
            'admin_section' => 'reference_data',
            'phase' => 'Phase 4',
        ],
        'content' => [
            'label' => 'Content & SEO',
            'description' => 'Programmatic SEO pages, blog resources, policies, success stories, and newsletters.',
            'enabled' => true,
            'public' => true,
            'admin_section' => 'content',
            'phase' => 'Phase 1 / Phase 4',
        ],
        'courses' => [
            'label' => 'Courses',
            'description' => 'Course catalog, learning pathways, institutional courses, and career upskilling.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'courses',
            'phase' => 'Future ecosystem',
        ],
        'internships' => [
            'label' => 'Internships',
            'description' => 'Internship listings, graduate pathways, and early-career placements.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'internships',
            'phase' => 'Future ecosystem',
        ],
        'apprenticeships' => [
            'label' => 'Apprenticeships',
            'description' => 'Apprenticeship listings, practical pathways, and work-based learning.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'internships',
            'phase' => 'Future ecosystem',
        ],
        'scholarships' => [
            'label' => 'Scholarships',
            'description' => 'Scholarship discovery, eligibility guidance, and education funding pathways.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'scholarships',
            'phase' => 'Future ecosystem',
        ],
        'career_coaching' => [
            'label' => 'Career Coaching',
            'description' => 'Coaching sessions, interview preparation, CV guidance, and job-search plans.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'coaching',
            'phase' => 'Future ecosystem',
        ],
        'employer_crm' => [
            'label' => 'Employer CRM',
            'description' => 'Employer relationship management, hiring pipelines, partner records, and account health.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'employer_crm',
            'phase' => 'Future ecosystem',
        ],
        'recruitment_agencies' => [
            'label' => 'Recruitment Agencies',
            'description' => 'Agency accounts, recruiter seats, licensing checks, bulk hiring, and overseas approval flows.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'agencies',
            'phase' => 'Future ecosystem',
        ],
        'skill_assessments' => [
            'label' => 'Skill Assessments',
            'description' => 'Skill tests, verified skills, assessment results, and job-readiness signals.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'assessments',
            'phase' => 'Future ecosystem',
        ],
        'credentials' => [
            'label' => 'Credential Verification',
            'description' => 'Credential verification, graduate records, certificate numbers, and institutional trust.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'credentials',
            'phase' => 'Future ecosystem',
        ],
        'university_placement' => [
            'label' => 'University Placement Portal',
            'description' => 'Institute, branch, student, graduate, employer partner, and placement reporting modules.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'placement',
            'phase' => 'Future ecosystem',
        ],
        'digital_certificates' => [
            'label' => 'Digital Certificates',
            'description' => 'Digital certificate issuing, certificate pages, QR validation, and certificate history.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'certificates',
            'phase' => 'Future ecosystem',
        ],
        'freelance_marketplace' => [
            'label' => 'Freelance Marketplace',
            'description' => 'Freelance profiles, project posts, proposals, milestone payments, and ratings.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'freelance',
            'phase' => 'Future ecosystem',
        ],
        'events' => [
            'label' => 'Events',
            'description' => 'Hiring events, webinars, workshops, and career sessions.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'events',
            'phase' => 'Future ecosystem',
        ],
        'career_fairs' => [
            'label' => 'Career Fairs',
            'description' => 'Career fairs, exhibitor booths, event registrations, and employer-candidate matching.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'career_fairs',
            'phase' => 'Future ecosystem',
        ],
        'mentorship' => [
            'label' => 'Mentorship',
            'description' => 'Mentor profiles, mentoring sessions, guided pathways, and industry advice.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'mentorship',
            'phase' => 'Future ecosystem',
        ],
        'networking' => [
            'label' => 'Networking',
            'description' => 'Professional connections, communities, groups, and career networking features.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'networking',
            'phase' => 'Future ecosystem',
        ],
        'talent_marketplace' => [
            'label' => 'Talent Marketplace',
            'description' => 'Verified talent pools, employer discovery, saved talent lists, and matching workflows.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'talent',
            'phase' => 'Future ecosystem',
        ],
        'ai_career' => [
            'label' => 'AI Career Advisor',
            'description' => 'AI career coach, CV parser, matching, recommendations, fraud detection, and recruiter assistant.',
            'enabled' => false,
            'public' => false,
            'admin_section' => 'ai',
            'phase' => 'Phase 5',
        ],
    ],
];
