<?php

declare(strict_types=1);

return [
    'default_timezone' => env('APP_TIMEZONE', 'Asia/Kuwait'),

    'records' => [
        ['name' => 'Afghanistan', 'nationality' => 'Afghanistan', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Albania', 'nationality' => 'Albania', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Algeria', 'nationality' => 'Algeria', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Andorra', 'nationality' => 'Andorra', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Angola', 'nationality' => 'Angola', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Antigua and Barbuda', 'nationality' => 'Antigua and Barbuda', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Argentina', 'nationality' => 'Argentina', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Armenia', 'nationality' => 'Armenia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Australia', 'nationality' => 'Australia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Austria', 'nationality' => 'Austria', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Azerbaijan', 'nationality' => 'Azerbaijan', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Bahamas', 'nationality' => 'Bahamas', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Bahrain', 'nationality' => 'Bahrain', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Bangladesh', 'nationality' => 'Bangladesh', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Barbados', 'nationality' => 'Barbados', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Belarus', 'nationality' => 'Belarus', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Belgium', 'nationality' => 'Belgium', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Belize', 'nationality' => 'Belize', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Benin', 'nationality' => 'Benin', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Bhutan', 'nationality' => 'Bhutan', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Bolivia', 'nationality' => 'Bolivia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Bosnia and Herzegovina', 'nationality' => 'Bosnia and Herzegovina', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Botswana', 'nationality' => 'Botswana', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Brazil', 'nationality' => 'Brazil', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Brunei', 'nationality' => 'Brunei', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Bulgaria', 'nationality' => 'Bulgaria', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Burkina Faso', 'nationality' => 'Burkina Faso', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Burundi', 'nationality' => 'Burundi', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Cabo Verde', 'nationality' => 'Cabo Verde', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Cambodia', 'nationality' => 'Cambodia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Cameroon', 'nationality' => 'Cameroon', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Canada', 'nationality' => 'Canada', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Central African Republic', 'nationality' => 'Central African Republic', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Chad', 'nationality' => 'Chad', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Chile', 'nationality' => 'Chile', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'China', 'nationality' => 'China', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Colombia', 'nationality' => 'Colombia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Comoros', 'nationality' => 'Comoros', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Congo', 'nationality' => 'Congo', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Costa Rica', 'nationality' => 'Costa Rica', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Cote dIvoire', 'nationality' => 'Cote dIvoire', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Croatia', 'nationality' => 'Croatia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Cuba', 'nationality' => 'Cuba', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Cyprus', 'nationality' => 'Cyprus', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Czechia', 'nationality' => 'Czechia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Democratic Republic of the Congo', 'nationality' => 'Democratic Republic of the Congo', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Denmark', 'nationality' => 'Denmark', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Djibouti', 'nationality' => 'Djibouti', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Dominica', 'nationality' => 'Dominica', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Dominican Republic', 'nationality' => 'Dominican Republic', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Ecuador', 'nationality' => 'Ecuador', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Egypt', 'nationality' => 'Egypt', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'El Salvador', 'nationality' => 'El Salvador', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Equatorial Guinea', 'nationality' => 'Equatorial Guinea', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Eritrea', 'nationality' => 'Eritrea', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Estonia', 'nationality' => 'Estonia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Eswatini', 'nationality' => 'Eswatini', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Ethiopia', 'nationality' => 'Ethiopia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Fiji', 'nationality' => 'Fiji', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Finland', 'nationality' => 'Finland', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'France', 'nationality' => 'France', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Gabon', 'nationality' => 'Gabon', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Gambia', 'nationality' => 'Gambia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Georgia', 'nationality' => 'Georgia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Germany', 'nationality' => 'Germany', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Ghana', 'nationality' => 'Ghana', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Greece', 'nationality' => 'Greece', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Grenada', 'nationality' => 'Grenada', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Guatemala', 'nationality' => 'Guatemala', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Guinea', 'nationality' => 'Guinea', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Guinea-Bissau', 'nationality' => 'Guinea-Bissau', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Guyana', 'nationality' => 'Guyana', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Haiti', 'nationality' => 'Haiti', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Honduras', 'nationality' => 'Honduras', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Hungary', 'nationality' => 'Hungary', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Iceland', 'nationality' => 'Iceland', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'India', 'nationality' => 'India', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Indonesia', 'nationality' => 'Indonesia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Iran', 'nationality' => 'Iran', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Iraq', 'nationality' => 'Iraq', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Ireland', 'nationality' => 'Ireland', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Israel', 'nationality' => 'Israel', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Italy', 'nationality' => 'Italy', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Jamaica', 'nationality' => 'Jamaica', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Japan', 'nationality' => 'Japan', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Jordan', 'nationality' => 'Jordan', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Kazakhstan', 'nationality' => 'Kazakhstan', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Kenya', 'nationality' => 'Kenya', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Kiribati', 'nationality' => 'Kiribati', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Kuwait', 'nationality' => 'Kuwait', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Kyrgyzstan', 'nationality' => 'Kyrgyzstan', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Laos', 'nationality' => 'Laos', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Latvia', 'nationality' => 'Latvia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Lebanon', 'nationality' => 'Lebanon', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Lesotho', 'nationality' => 'Lesotho', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Liberia', 'nationality' => 'Liberia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Libya', 'nationality' => 'Libya', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Liechtenstein', 'nationality' => 'Liechtenstein', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Lithuania', 'nationality' => 'Lithuania', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Luxembourg', 'nationality' => 'Luxembourg', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Madagascar', 'nationality' => 'Madagascar', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Malawi', 'nationality' => 'Malawi', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Malaysia', 'nationality' => 'Malaysia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Maldives', 'nationality' => 'Maldives', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Mali', 'nationality' => 'Mali', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Malta', 'nationality' => 'Malta', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Marshall Islands', 'nationality' => 'Marshall Islands', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Mauritania', 'nationality' => 'Mauritania', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Mauritius', 'nationality' => 'Mauritius', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Mexico', 'nationality' => 'Mexico', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Micronesia', 'nationality' => 'Micronesia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Moldova', 'nationality' => 'Moldova', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Monaco', 'nationality' => 'Monaco', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Mongolia', 'nationality' => 'Mongolia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Montenegro', 'nationality' => 'Montenegro', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Morocco', 'nationality' => 'Morocco', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Mozambique', 'nationality' => 'Mozambique', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Myanmar', 'nationality' => 'Myanmar', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Namibia', 'nationality' => 'Namibia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Nauru', 'nationality' => 'Nauru', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Nepal', 'nationality' => 'Nepal', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Netherlands', 'nationality' => 'Netherlands', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'New Zealand', 'nationality' => 'New Zealand', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Nicaragua', 'nationality' => 'Nicaragua', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Niger', 'nationality' => 'Niger', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Nigeria', 'nationality' => 'Nigeria', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'North Korea', 'nationality' => 'North Korea', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'North Macedonia', 'nationality' => 'North Macedonia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Norway', 'nationality' => 'Norway', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Oman', 'nationality' => 'Oman', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Pakistan', 'nationality' => 'Pakistan', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Palau', 'nationality' => 'Palau', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Palestine', 'nationality' => 'Palestine', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Panama', 'nationality' => 'Panama', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Papua New Guinea', 'nationality' => 'Papua New Guinea', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Paraguay', 'nationality' => 'Paraguay', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Peru', 'nationality' => 'Peru', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Philippines', 'nationality' => 'Philippines', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Poland', 'nationality' => 'Poland', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Portugal', 'nationality' => 'Portugal', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Qatar', 'nationality' => 'Qatar', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Romania', 'nationality' => 'Romania', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Russia', 'nationality' => 'Russia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Rwanda', 'nationality' => 'Rwanda', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Saint Kitts and Nevis', 'nationality' => 'Saint Kitts and Nevis', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Saint Lucia', 'nationality' => 'Saint Lucia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Saint Vincent and the Grenadines', 'nationality' => 'Saint Vincent and the Grenadines', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Samoa', 'nationality' => 'Samoa', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'San Marino', 'nationality' => 'San Marino', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Sao Tome and Principe', 'nationality' => 'Sao Tome and Principe', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Saudi Arabia', 'nationality' => 'Saudi Arabia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Senegal', 'nationality' => 'Senegal', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Serbia', 'nationality' => 'Serbia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Seychelles', 'nationality' => 'Seychelles', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Sierra Leone', 'nationality' => 'Sierra Leone', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Singapore', 'nationality' => 'Singapore', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Slovakia', 'nationality' => 'Slovakia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Slovenia', 'nationality' => 'Slovenia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Solomon Islands', 'nationality' => 'Solomon Islands', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Somalia', 'nationality' => 'Somalia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'South Africa', 'nationality' => 'South Africa', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'South Korea', 'nationality' => 'South Korea', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'South Sudan', 'nationality' => 'South Sudan', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Spain', 'nationality' => 'Spain', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Sri Lanka', 'nationality' => 'Sri Lanka', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Sudan', 'nationality' => 'Sudan', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Suriname', 'nationality' => 'Suriname', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Sweden', 'nationality' => 'Sweden', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Switzerland', 'nationality' => 'Switzerland', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Syria', 'nationality' => 'Syria', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Taiwan', 'nationality' => 'Taiwan', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Tajikistan', 'nationality' => 'Tajikistan', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Tanzania', 'nationality' => 'Tanzania', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Thailand', 'nationality' => 'Thailand', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Timor-Leste', 'nationality' => 'Timor-Leste', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Togo', 'nationality' => 'Togo', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Tonga', 'nationality' => 'Tonga', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Trinidad and Tobago', 'nationality' => 'Trinidad and Tobago', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Tunisia', 'nationality' => 'Tunisia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Turkey', 'nationality' => 'Turkey', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Turkmenistan', 'nationality' => 'Turkmenistan', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Tuvalu', 'nationality' => 'Tuvalu', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'UAE', 'nationality' => 'UAE', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Uganda', 'nationality' => 'Uganda', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Ukraine', 'nationality' => 'Ukraine', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'United Kingdom', 'nationality' => 'United Kingdom', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'United States', 'nationality' => 'United States', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Uruguay', 'nationality' => 'Uruguay', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Uzbekistan', 'nationality' => 'Uzbekistan', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Vanuatu', 'nationality' => 'Vanuatu', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Vatican City', 'nationality' => 'Vatican City', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Venezuela', 'nationality' => 'Venezuela', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Vietnam', 'nationality' => 'Vietnam', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Yemen', 'nationality' => 'Yemen', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Zambia', 'nationality' => 'Zambia', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
        ['name' => 'Zimbabwe', 'nationality' => 'Zimbabwe', 'timezone' => env('APP_TIMEZONE', 'Asia/Kuwait')],
    ],
];
