<?php

declare(strict_types=1);

return [
    'brand' => [
        'name' => env('JOBPORTAL_BRAND_NAME', 'Global Career Connect'),
        'tagline' => 'Connecting global employers with skilled, verified, and job-ready talent.',
        'powered_by' => 'Powered by ICSA Group / NAS International College of London',
        'description' => 'An international career and hiring platform where job seekers worldwide can build professional profiles, upload CVs and video introductions, showcase portfolios, and connect with verified employers globally.',
    ],

    'stats' => [
        ['label' => 'Target countries', 'value' => '190+'],
        ['label' => 'Job categories', 'value' => '40+'],
        ['label' => 'Supported currencies', 'value' => '15'],
        ['label' => 'Trust badges planned', 'value' => '12'],
    ],

    'countries' => [
        'Kuwait', 'UAE', 'Saudi Arabia', 'Qatar', 'Bahrain', 'Oman', 'United Kingdom',
        'Canada', 'Australia', 'United States', 'European countries', 'Germany', 'Pakistan',
        'Philippines', 'India', 'Nepal', 'Bangladesh', 'Sri Lanka', 'Kenya',
        'Africa and other regions',
    ],

    'currencies' => ['KWD', 'AED', 'SAR', 'QAR', 'BHD', 'OMR', 'GBP', 'USD', 'CAD', 'AUD', 'EUR', 'PKR', 'INR', 'PHP', 'NPR', 'BDT', 'LKR'],

    'languages' => ['English', 'Arabic', 'Tagalog', 'Urdu', 'Hindi', 'French', 'Spanish'],

    'salary_types' => ['Monthly', 'Hourly', 'Annual', 'Daily', 'Project-based', 'Commission-based', 'Negotiable', 'Undisclosed'],

    'categories' => [
        'Caregiving', 'Healthcare Support', 'Hospitality', 'Office Administration', 'Accounting',
        'Information Technology', 'Cybersecurity', 'AI & Data', 'Education & Training',
        'Drivers & Technicians', 'Design & Creative', 'Remote Work', 'Fresh Graduate',
        'Skilled Worker', 'Freelance Projects',
    ],

    'candidate_types' => [
        'Job seekers from any country', 'Recruitment agencies', 'Freelancers and remote workers',
        'Fresh graduates', 'Skilled workers', 'Professional candidates', 'Blue-collar workers',
        'Caregivers', 'IT professionals', 'Office/admin workers', 'Healthcare support workers',
        'Hospitality workers', 'Teachers/trainers', 'Drivers/technicians', 'Accountants',
        'Designers', 'Programmers', 'AI/data/cybersecurity professionals',
        'Optional ICSA/NAS verified graduate category',
    ],

    'employer_types' => [
        'Employers from any country', 'Small businesses', 'Large companies', 'Training institutes',
        'Hospitals/clinics', 'Care homes', 'Hotels/restaurants', 'Recruitment agencies',
        'Remote-first companies', 'International employers', 'Startups',
        'Government-approved manpower agencies', 'Education providers',
    ],

    'jobs' => [
        [
            'slug' => 'caregiver-uk-visa-sponsorship',
            'title' => 'Senior Caregiver',
            'company' => 'Northbridge Care Group',
            'city' => 'Manchester',
            'country' => 'United Kingdom',
            'mode' => 'On-site',
            'salary' => 'GBP 2,100 - 2,650 monthly',
            'type' => 'Full-time',
            'category' => 'Caregiving',
            'badges' => ['Visa sponsorship', 'Accommodation support', 'Verified employer'],
            'urgent' => true,
            'deadline' => '2026-09-30',
            'vacancies' => 18,
            'description' => 'Support elderly residents with daily care, dignity, mobility, medication reminders, and safe routines in a regulated care environment.',
            'responsibilities' => ['Assist residents with personal care and mobility', 'Maintain accurate care notes', 'Support meal routines and companionship', 'Follow safeguarding and health policies'],
            'skills' => ['Patient care', 'English communication', 'Safeguarding awareness', 'Teamwork'],
            'requirements' => ['Caregiving training or relevant experience', 'Basic English', 'Willingness to relocate', 'Clean employment record'],
            'benefits' => ['Visa sponsorship pathway', 'Accommodation guidance', 'Paid training', 'Overtime available'],
        ],
        [
            'slug' => 'remote-laravel-developer-canada',
            'title' => 'Remote Laravel Developer',
            'company' => 'MapleCloud Labs',
            'city' => 'Toronto',
            'country' => 'Canada',
            'mode' => 'Remote',
            'salary' => 'USD 2,800 - 4,200 monthly',
            'type' => 'Contract',
            'category' => 'Information Technology',
            'badges' => ['Remote', 'Portfolio required', 'Verified employer'],
            'urgent' => false,
            'deadline' => '2026-09-15',
            'vacancies' => 4,
            'description' => 'Build and maintain Laravel applications for international SaaS clients with clean APIs, queues, tests, and secure admin workflows.',
            'responsibilities' => ['Develop Laravel features', 'Write automated tests', 'Review pull requests', 'Integrate third-party APIs'],
            'skills' => ['Laravel', 'MySQL/MariaDB', 'REST APIs', 'Git', 'Tailwind CSS'],
            'requirements' => ['2+ years Laravel experience', 'Public portfolio or GitHub', 'Remote collaboration skills'],
            'benefits' => ['Remote-first team', 'Flexible schedule', 'Long-term contract option'],
        ],
        [
            'slug' => 'hotel-front-office-dubai',
            'title' => 'Front Office Executive',
            'company' => 'Pearl Vista Hotels',
            'city' => 'Dubai',
            'country' => 'UAE',
            'mode' => 'On-site',
            'salary' => 'AED 3,500 - 4,500 monthly',
            'type' => 'Full-time',
            'category' => 'Hospitality',
            'badges' => ['Urgent hiring', 'Transportation provided', 'Verified employer'],
            'urgent' => true,
            'deadline' => '2026-08-25',
            'vacancies' => 6,
            'description' => 'Welcome guests, manage check-in and check-out, coordinate bookings, and provide polished hospitality service.',
            'responsibilities' => ['Handle reservations', 'Manage guest requests', 'Coordinate with housekeeping', 'Process front-desk reports'],
            'skills' => ['Customer service', 'English', 'MS Office', 'Hospitality etiquette'],
            'requirements' => ['Hospitality diploma preferred', '1+ year hotel experience', 'Professional appearance'],
            'benefits' => ['Transportation', 'Duty meals', 'Medical insurance'],
        ],
        [
            'slug' => 'cybersecurity-analyst-kuwait',
            'title' => 'Junior Cybersecurity Analyst',
            'company' => 'GulfSecure Systems',
            'city' => 'Kuwait City',
            'country' => 'Kuwait',
            'mode' => 'Hybrid',
            'salary' => 'KWD 450 - 650 monthly',
            'type' => 'Fresh graduate',
            'category' => 'Cybersecurity',
            'badges' => ['Fresh graduates welcome', 'Training provided', 'Verified employer'],
            'urgent' => false,
            'deadline' => '2026-10-05',
            'vacancies' => 3,
            'description' => 'Monitor alerts, support incident response, prepare reports, and learn security operations in a supervised team.',
            'responsibilities' => ['Review SIEM alerts', 'Document incidents', 'Support vulnerability checks', 'Escalate suspicious activity'],
            'skills' => ['Networking basics', 'Linux basics', 'Security fundamentals', 'Report writing'],
            'requirements' => ['Cybersecurity course or certification', 'Analytical mindset', 'Willingness to work shifts'],
            'benefits' => ['Mentorship', 'Certification support', 'Hybrid work'],
        ],
    ],

    'candidates' => [
        ['name' => 'Ayesha Khan', 'headline' => 'Certified Caregiver open to UK roles', 'country' => 'Pakistan', 'badges' => ['Verified Profile', 'Video Profile', 'Verified Certificate'], 'skills' => ['Elder care', 'First aid', 'English']],
        ['name' => 'Daniel Reyes', 'headline' => 'Remote Laravel developer with SaaS portfolio', 'country' => 'Philippines', 'badges' => ['Portfolio Available', 'Open to Remote Work'], 'skills' => ['Laravel', 'Vue', 'APIs']],
        ['name' => 'Mariam Al-Sabah', 'headline' => 'Junior cybersecurity analyst', 'country' => 'Kuwait', 'badges' => ['Verified ICSA Graduate', 'Verified Skill'], 'skills' => ['SOC', 'Linux', 'Networking']],
    ],

    'badges' => [
        'Verified Profile', 'Verified Email', 'Verified Phone', 'Verified Certificate', 'Verified Skill',
        'Verified ICSA Graduate', 'Verified NAS Graduate', 'Video Profile Available',
        'Portfolio Available', 'Open to Remote Work', 'Available Immediately', 'Verified Employer',
    ],

    'packages' => [
        ['name' => 'Free Employer Account', 'price' => 'Free', 'features' => ['Company profile', 'Limited job posting trial', 'Admin approval required']],
        ['name' => 'Standard Job Post', 'price' => 'Per post', 'features' => ['30 days active', 'Applicant management', 'Normal visibility']],
        ['name' => 'Featured Job Post', 'price' => 'Premium', 'features' => ['Highlighted listing', 'Homepage promotion', 'Top search position']],
        ['name' => 'Urgent Hiring Package', 'price' => 'Priority', 'features' => ['Urgent badge', 'Fast candidate alert', 'Optional social promotion']],
        ['name' => 'CV Database Access', 'price' => 'Credits', 'features' => ['Basic preview', 'Reveal full CV/contact with credits', 'Saved searches']],
        ['name' => 'Premium Employer Package', 'price' => 'Premium', 'features' => ['Multiple job posts', 'CV downloads', 'Video profile access', 'Employer branding page', 'Analytics', 'Priority support']],
        ['name' => 'Recruitment Agency Package', 'price' => 'Enterprise', 'features' => ['Multiple recruiter accounts', 'Bulk job posting', 'Applicant exports']],
    ],

    'roadmap' => [
        ['phase' => 'Phase 1', 'title' => 'Global MVP', 'items' => ['Homepage', 'Global job search', 'Job detail page', 'Candidate and employer registration', 'Job posting foundation', 'Admin approval', 'Basic SEO']],
        ['phase' => 'Phase 2', 'title' => 'Candidate Profile Power', 'items' => ['Video profile', 'Portfolio upload', 'Public profile link', 'Profile completion score', 'Saved jobs', 'Certificate upload']],
        ['phase' => 'Phase 3', 'title' => 'Employer Monetization', 'items' => ['Paid job posts', 'Featured jobs', 'CV search credits', 'Advanced candidate search', 'Employer analytics']],
        ['phase' => 'Phase 4', 'title' => 'International Growth', 'items' => ['Multi-currency', 'Multi-language', 'Country SEO pages', 'Company directory', 'Career blog', 'WhatsApp sharing']],
        ['phase' => 'Phase 5', 'title' => 'AI and Automation', 'items' => ['AI CV parser', 'AI job matching', 'AI scam detection', 'AI cover letters', 'AI recruiter assistant']],
    ],

    'ecosystem_modules' => [
        'Jobs', 'Courses', 'Internships', 'Apprenticeships', 'Scholarships', 'Career Coaching',
        'Employer CRM', 'Recruitment Agencies', 'Skill Assessments', 'AI Career Advisor',
        'University Placement Portal', 'Digital Certificates', 'Credential Verification',
        'Freelance Marketplace', 'Mentorship', 'Events', 'Career Fairs', 'Talent Marketplace',
    ],

    'policies' => [
        'terms' => 'Terms and Conditions',
        'privacy' => 'Privacy Policy',
        'cookies' => 'Cookie Policy',
        'employer-terms' => 'Employer Terms',
        'candidate-terms' => 'Candidate Terms',
        'refunds' => 'Refund Policy',
        'job-posting-rules' => 'Job Posting Rules',
        'anti-scam' => 'Anti-Scam Policy',
        'data-deletion' => 'Data Deletion Request',
        'gdpr-consent' => 'GDPR-style Consent',
        'equal-opportunity' => 'Equal Opportunity Policy',
        'visa-job-disclaimer' => 'Visa and Job Guarantee Disclaimer',
    ],

    'seo_pages' => [
        'jobs-in-kuwait' => ['title' => 'Jobs in Kuwait', 'focus' => 'Kuwait hiring across admin, accounting, hospitality, IT, healthcare support, and skilled worker roles.'],
        'jobs-in-dubai' => ['title' => 'Jobs in Dubai', 'focus' => 'Dubai opportunities with verified employers, hospitality openings, office jobs, and skilled worker roles.'],
        'jobs-in-london' => ['title' => 'Jobs in London', 'focus' => 'London career opportunities for local and overseas applicants where employers accept international profiles.'],
        'jobs-in-canada' => ['title' => 'Jobs in Canada', 'focus' => 'Canada-focused roles including remote tech, healthcare support, and visa-sponsorship friendly listings.'],
        'jobs-in-australia' => ['title' => 'Jobs in Australia', 'focus' => 'Australia opportunities for skilled workers, graduates, and remote-ready professionals.'],
        'remote-jobs' => ['title' => 'Remote Jobs', 'focus' => 'International remote roles across software, design, support, accounting, education, and marketing.'],
        'caregiver-jobs-in-uk' => ['title' => 'Caregiver Jobs in the UK', 'focus' => 'UK caregiving roles with verified employers, training expectations, accommodation details, and visa-support information where available.'],
        'office-admin-jobs-in-dubai' => ['title' => 'Office Admin Jobs in Dubai', 'focus' => 'Dubai office administration roles for organized candidates with communication, documentation, and customer-service skills.'],
        'cybersecurity-jobs-in-canada' => ['title' => 'Cybersecurity Jobs in Canada', 'focus' => 'Canada cybersecurity roles for analysts, SOC learners, graduates, and professionals with verified skills and portfolios.'],
        'accounting-jobs-in-kuwait' => ['title' => 'Accounting Jobs in Kuwait', 'focus' => 'Kuwait accounting and finance openings for junior accountants, bookkeepers, auditors, and payroll professionals.'],
        'visa-sponsorship-jobs' => ['title' => 'Visa Sponsorship Jobs', 'focus' => 'Jobs where employers may support visa, work permit, or relocation processes without guaranteeing outcomes.'],
        'filipino-job-seekers' => ['title' => 'Jobs for Filipino Job Seekers', 'focus' => 'International and remote opportunities for Filipino professionals, skilled workers, caregivers, hospitality staff, and tech candidates.'],
        'fresh-graduate-jobs' => ['title' => 'Fresh Graduate Jobs', 'focus' => 'Entry-level roles, internships, apprenticeships, and first-job pathways for graduates globally.'],
        'skilled-workers-jobs-abroad' => ['title' => 'Skilled Worker Jobs Abroad', 'focus' => 'International skilled worker openings with verified employers and clear benefit information.'],
        'jobs-by-country' => ['title' => 'Jobs by Country', 'focus' => 'Browse international openings by destination country, region, relocation support, and employer verification status.'],
        'jobs-by-city' => ['title' => 'Jobs by City', 'focus' => 'Find roles in major hiring cities with clear country, currency, and work-arrangement information.'],
        'jobs-by-category' => ['title' => 'Jobs by Category', 'focus' => 'Search opportunities by caregiving, IT, hospitality, accounting, office administration, design, skilled trades, and more.'],
        'jobs-by-skill' => ['title' => 'Jobs by Skill', 'focus' => 'Discover openings based on practical skills, certifications, portfolios, languages, and verified training.'],
        'jobs-by-salary' => ['title' => 'Jobs by Salary', 'focus' => 'Compare roles by disclosed salary, currency, pay period, benefits, and package transparency.'],
        'jobs-by-employment-type' => ['title' => 'Jobs by Employment Type', 'focus' => 'Browse full-time, part-time, contract, freelance, temporary, internship, and apprenticeship jobs.'],
        'jobs-by-language' => ['title' => 'Jobs by Language', 'focus' => 'Find opportunities by English, Arabic, Tagalog, Urdu, Hindi, French, Spanish, and future language requirements.'],
        'jobs-by-visa-sponsorship' => ['title' => 'Jobs by Visa Sponsorship', 'focus' => 'Review jobs where employers may offer visa, work-permit, or relocation support without guaranteeing approval.'],
        'remote-jobs-by-category' => ['title' => 'Remote Jobs by Category', 'focus' => 'Search remote work by skill area, category, country eligibility, schedule, and portfolio requirements.'],
        'international-jobs' => ['title' => 'International Jobs', 'focus' => 'Global jobs for candidates seeking cross-border, remote, hybrid, or relocation-friendly opportunities.'],
        'overseas-jobs' => ['title' => 'Overseas Jobs', 'focus' => 'Overseas job listings with clear employer information, benefits, contract details, and safety guidance.'],
        'caregiver-jobs-abroad' => ['title' => 'Caregiver Jobs Abroad', 'focus' => 'Caregiving roles outside your home country with training, language, care-setting, and benefit expectations.'],
        'healthcare-support-jobs' => ['title' => 'Healthcare Support Jobs', 'focus' => 'Healthcare assistant, clinic support, care support, and patient service jobs across supported countries.'],
        'it-jobs-abroad' => ['title' => 'IT Jobs Abroad', 'focus' => 'International IT openings for developers, support specialists, cloud talent, cybersecurity learners, and remote teams.'],
        'office-admin-jobs-abroad' => ['title' => 'Office Admin Jobs Abroad', 'focus' => 'Office administration, receptionist, documentation, customer-service, and operations support jobs abroad.'],
    ],

    'blog_categories' => [
        'Job search tips',
        'CV/resume writing',
        'Interview preparation',
        'Work abroad guide',
        'Remote work guide',
        'Visa sponsorship job guide',
        'Country-wise job guides',
        'Career development',
        'Skill-based careers',
        'Employer hiring tips',
        'Recruitment trends',
        'Success stories',
    ],

    'blog_topics' => [
        'How to Find Jobs Abroad Without Paying Agents',
        'How to Prepare a Professional Video CV',
        'Best Countries Hiring Caregivers',
        'How to Write a CV for Gulf Jobs',
        'How to Write a Resume for Canada',
        'Best Skills for Remote Jobs',
        'How to Avoid Fake Job Offers',
        'How to Apply for Visa Sponsorship Jobs',
        'Top Skills Employers Look For in 2026',
        'How Fresh Graduates Can Get Their First Job',
    ],
];
